### ISSUE TITLE
Bug: Can't run any tests with Firefox browser

### ISSUE THREAD

**Issue by IT-Cru** [julienloizelet/ddev-playwright#21] opened 2024-04-11 15:44 UTC
When it comes to running tests with Firefox browser all tests are failing in DDEV playwright container. Running same tests in our CI Playwright job which is using playwright:latest docker image and same package.json from tests/Playwright folder all is working fine.

I could only get it running, when I remove this PRE variable handling to run npx playwright commands triggered via ddev playwright command.

Is this PRE variable really needed in this DDEV command?

**Comment by julienloizelet** [comment] 2024-04-12 06:13
Hi @IT-Cru , thanks for reporting this.

I did a few tests and indeed, all tests failed with firefox.

Even when I remove the PRE part of the `ddev playwright` command, it failed: could you share with me some details on how you succeed ?

Regarding the PRE variable, I have to figure out if this is still necessary, but, looking at the [pull request](https://github.com/julienloizelet/ddev-playwright/pull/7) that introduces it, it seems to have 2 purposes: 

- Run as the pwuser (the one that owns all the KasmVNC stuff)
- Persist local browsers.

Will have to figure out what could be the root cause.

There is also a known bug with Firefox and docker: https://github.com/microsoft/playwright/issues/16491
and I wonder if it could be related.

@Biont : if you read this :) , do you have any hint about a possible issue with the PRE variable ?

**Comment by julienloizelet** [comment] 2024-04-12 08:51
With a little more debugging, I got the same type of error message as in https://github.com/microsoft/playwright/issues/7341#issuecomment-869159912

So I guess there's a permission problem for `pwuser` and some firefox files/directories.

(And when we remove the PRE variable, we run command as root, that's why it probably avoid the problem, not sure)

Will try to investigate more on this when possible.

Thanks

**Comment by IT-Cru** [comment] 2024-04-18 10:03
For using Playwright for e2e testing using pwuser is not really needed I would say.
https://playwright.dev/docs/docker#end-to-end-tests

But maybe people want to use DDEV playwright docker not only for e2e testing.

An option could be to enable this PRE sudo pwuser handling with some additional parameter of ddev playwright command only if people want to use Playwright not as e2e testing solution in their DDEV project.

**Comment by julienloizelet** [comment] 2024-04-19 05:54
> For using Playwright for e2e testing using pwuser is not really needed I would say. https://playwright.dev/docs/docker#end-to-end-tests
> 
> But maybe people want to use DDEV playwright docker not only for e2e testing.
> 
> An option could be to enable this PRE sudo pwuser handling with some additional parameter of ddev playwright command only if people want to use Playwright not as e2e testing solution in their DDEV project.

The `pwuser` was introduced because there was a need, for some people, to use KasmVNC (Adding a VNC server and xvfb for headed operation).

I agree that we could add an option to just run every command as root (i.e without the PRE variable).

But so far I've got a few tests that I haven't been able to run successfully with Firefox, even after removing this PRE variable; I don't know if I'm doing something wrong or if it just doesn't work.

There are so many unresolved issues with Firefox and the error message I have: https://github.com/microsoft/playwright/issues?q=is%3Aissue+glxtest%3A+libpci+missing

I don't have much time at the moment to work on it. I hope to have a look at it as soon as possible.

Thanks

**Comment by julienloizelet** [comment] 2024-04-20 06:46
Hi @IT-Cru ,

Could you do a test for me ?

You've said that you were able to run your tests by removing the `PRE` variable.

As a workaround (and for debugging purpose), could you try to use this kind of command:

```
ddev exec -s playwright "cd /var/www/html/tests/Playwright && npx playwright test"
```
  
With this, the script will run without the PRE variable.

Does it work for you ?

It doesn't for me and, debugging with 

```
ddev exec -s playwright "cd /var/www/html/tests/Playwright && DEBUG=pw:browser npx playwright test"
```

leads me to the error: `Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.146315) [GFX1-]: glxtest: libpci missing +102m`

Thanks

**Comment by IT-Cru** [comment] 2024-04-23 12:32
Hi @julienloizelet ,

for me running via your ddev exec command works fine.

```
ddev exec -s playwright "cd /var/www/html/tests/Playwright && npx playwright test"
```

I've also checked that libpci is not installed at playwright docker container .

```
apt-get install libpci3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  pci.ids
The following NEW packages will be installed:
  libpci3 pci.ids
0 upgraded, 2 newly installed, 0 to remove and 12 not upgraded.
Need to get 241 kB of archives.
After this operation, 1329 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

Im using FROM mcr.microsoft.com/playwright:focal in Dockerfile located in .ddev/playwright-build folder.

My playwright package.json:

```
{
  "license": "MIT",
  "dependencies": {
    "@playwright/test": "^1.40.0",
    "dotenv": "^16.0.3"
  }
}
```

When running ddev playwright without removing PRE variable logic running tests with Firefox fails.

Do you running on Intel or ARM based CPU?

My host machine is a MacBook Pro with M3 ARM. So maybe here also something could be somehow different in Docker containers. I run in some differences also in the past when switching from Intel to ARM based Mac when detecting installed apps from homebrew. So maybe Firefox also have some difference behaviors depending on CPU architecture.

What I haven't tested yet is to switch `USER pwuser` in Dockerfile after all this apt installs back from root to pwuser again to avoid using sudo commands.

**Comment by julienloizelet** [comment] 2024-04-25 01:35
Hi @IT-Cru ,
Thanks a lot for your message.

My tests were run under Linux (amd64). 

Some tests passed, but a lot failed (only with firefox).

As you've noticed, I'm pretty sure that the `libpci` error message is not related to the root issue. (Because it works for you and it is not installed in the playwright container).

I will try to install it anyway and see if I can have more info.

I will also try to test on a Mac M2 (I guess it's ARM, will see).

Just out of curiosity, I assume you don't need to run the test in head mode (with the `--headed` parameter) ?

Because the point of this `pwuser` was to be able to run in head mode and see the result thanks to KasmVNC.
 
I ask because I could add an option like `--use_root` to bypass the `PRE` variable, but then, I guess all the KasmVNC feature will not work with this option.

Or maybe I could just try not to create this pwuser and use the root user everywhere. I'm just thinking out loud...

Thanks again

**Comment by julienloizelet** [comment] 2024-04-28 04:17
Just for information, I've done some more tests.

Installing `libpci` does not resolve my issue: libpci related error disappears but firefox still hangs.

On the other hand, I tested the example test provided by `npm init playwright@latest` command: 

```
 // @ts-check
const { test, expect } = require('@playwright/test');

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
```
And all tests passed even with Firefox.

What I can conclude is that only some tests are failing with Firefox, not all. In my case, it's probably the firefox/magento2 combination that makes it crash.

@IT-Cru , please let me know if you'd like me to add an option to remove the `-u pwuser` part of the `PRE` variable (I guess we can keep the `PLAYWRIGHT_BROWSERS_PATH=0` part ? ) . 
I have no idea why this makes your tests pass; but if it makes it easier for you to use, I'll add it.

Thanks

**Comment by julienloizelet** [comment] 2024-11-13 07:30
Today I tried again and all the tests were successful on Firefox.

I think something has changed upstream (Playwright? Firefox?).

Happy to continue the conversation here or elsewhere, but closing for now.

**Closed by julienloizelet** 2024-11-13 07:30 UTC
Labels: bug
